import Head from 'next/head'
import Image from 'next/image'
import MiPrimerComponente from '../components/MiPrimerComponente'
import Link from 'next/link'


/*
  Es una librería de código abierto que se utiliza principalmente para construir interfaces; es decir, es una tecnología enfocada en la interactividad.
  Es Declarativo, es decir, se le dice qué se quiere hacer y no cómo se quiere hacer.
  Esta basado en componentes, es decir, separas la lógica de la aplicacion en pequeños bloques para despues
  reutilizarlas y crear aplicaciones mas escalables.
*/
export default function Home() {
  return (
    <div className='min-h-screen bg-black'>
      <Head>
        <title>Mi primera pagina con react</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=''>
        <MiPrimerComponente />
        <MiPrimerComponente title='Adios Mundo'/>
      </main>

      <footer className=''>
        <Link href={'/login'}><a className='block text-2xl text-center font-bold text-white underline decoration-solid decoration-purple-500'>Login</a></Link>
      </footer>
    </div>
  )
}
