import Link from 'next/link'
import Head from 'next/head'
import MiPrimerComponente from '../components/MiPrimerComponente' 

export default function Login() {
  return (
    <div className='min-h-screen bg-black'>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MiPrimerComponente title='Login'/>
      <Link href={'/'}><a className='block text-white text-2xl text-center font-bold underline decoration-solid decoration-purple-500'>Home</a></Link>
    </div>
  )
}